//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTrungTamNN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUOIHOC
    {
        public int BuoiHocID { get; set; }
        public string TenBuoiHoc { get; set; }
        public string PhongHoc { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int TeacherID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
